name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-cpu.txt

      - name: Build executables
        run: |
          python build.py

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/WhisperPGE.exe
            build/updater.exe
            build/app/version.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
