name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch==2.0.1+cpu torchaudio==2.0.2+cpu --index-url https://download.pytorch.org/whl/cpu
          pip install openai-whisper>=20231117 numpy>=1.21.0 requests>=2.31.0 packaging>=23.2 pyinstaller>=6.1

      - name: Build executables
        run: |
          python build.py

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/WhisperPGE-Installer.exe
            build/app/version.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
